-keep class com.vahider.logz.** { *; }
-keep interface com.vahider.logz.** { *; }
-keepclasseswithmembernames class com.vahider.logz.** { *; }
-keepclasseswithmembernames interface com.vahider.logz.** { *; }
-dontwarn com.vahider.logz.**